Introducing the streamlined Makefile-creation toolbox

diff --git a/examples/newexample b/examples/newexample
--- a/examples/newexample
+++ b/examples/newexample
@@ -1,52 +1,76 @@
 #!/usr/bin/env bash
 
-# Use this script to create a bare minimum example 
-# 
-# Usage:
-#   ./newexample name
-#
+PARCASL_EXAMPLES_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
+PARCASL_DIR="$(dirname $PARCASL_EXAMPLES_DIR)"
 
-# creates a .pro file 
+# creates a .pro file
+# (In the following, EOF works as a delimiter for the text that needs to be copied as is to the .pro file)
 function create_pro() {
-cat > $1/$1.pro << EOF
+cat > $1.pro << EOF
 # --------------------------------------------------------------
 # This is a qmake script for generating makefiles. Please read
-# this short comment before changing this file. 
+# this short comment before changing this file.
 #
-# Following build systems are supported:
-#   * macx (default)
-#   * linux
-#   * stampede
+# The build environment (specific paths to external libraries,
+# compilers, etc.) needs to be fully determined in
+# $PARCASL_DIR/qmake/${CASL_P4EST_USER}.pri
 #
-# To use either of these systems, you can pass in the correct
-# value to qmake, e.g. to build for stamepde system:
-#   qmake example.pro CONFIG+="stampede"
+# Some additional configuration settings can be defined here below
+# with
+#     CONFIG += "options"
+# Available options are: (2d or 3d), (debug or release), log, profile, ...
+# Regarding the (2d or 3d) and/or (debug or release) options, it is
+# advised to configure separate build directories in the Qt configuration
+# settings to avoid mismatch of incompatible and/or inconsistent object
+# files...
 #
-# You can also modify the CONFIG variable below, but remember
-# that doing so will prevent you from using the same script on
-# different systems.
+# Otherwise, one can pass in the desired value to qmake, e.g. to create a
+# Makefile for building with release and 2d:
+#   qmake example.pro CONFIG+="2d release"
 #
-#   *** PLEASE DO NOT ADD YOUR CONFIG SCRIPT TO REPOSITORY ***
+#   *** PLEASE DO NOT ADD CONFIG SCRIPTS TO THE REPOSITORY ***
 #
 # --------------------------------------------------------------
-CONFIG += 2d
-include(../../qmake/libparcasl.pri)
 
-2d {
-  TARGET   = $1_2d
-  SOURCES += main_2d.cpp
-} 3d {
-  TARGET   = $1_3d
-  SOURCES += main_3d.cpp
-}
+CASL_P4EST = $2
+
+TARGET   = $1
+
+CONFIG += # this(these) one(s) is(are) for the user to set!
+
+include(\$\$CASL_P4EST/qmake/${CASL_P4EST_USER}.pri) # file containing paths to external libraries (PETSc, p4est, voro++, boost, matlab, mpi)
+include(\$\$CASL_P4EST/qmake/common.pri) # linking libraries and setting common for all project parameters
+include(\$\$CASL_P4EST/examples/$1/$1.pri) # list of files for this particular project
 
 EOF
 }
 
-# creates a sample main_2d.cpp and main_3d.cpp
-function create_main() {
+# creates a .pri file
+# (In the following, EOF works as a delimiter for the text that needs to be copied as is to the .pri file)
+function create_pri() {
+cat > $1.pri << EOF
+
+CONFIG(2d, 2d|3d): {
+  SOURCES += \$\$PWD/main_2d.cpp
+}
+
+CONFIG(3d, 2d|3d): {
+  SOURCES += \$\$PWD/main_3d.cpp
+}
+
+include(\$\$PWD/../../qmake/libparcasl.pri)
+
+EOF
+}
+
+
+# creates a bare minimum example
+# (In the following, EOF works as a delimiter for the text that needs to be copied as is to the main file)
+
+# creates a bare minimum main_2d.cpp and main_3d.cpp
+function create_dummy_main() {
 cat > $1/main_2d.cpp << EOF
-/* 
+/*
  * Title: $1
  * Description:
  * Author: $(git config user.name)
@@ -79,7 +103,7 @@ cat > $1/main_2d.cpp << EOF
 using namespace std;
 
 int main(int argc, char** argv) {
-  
+
   // prepare parallel enviroment
   mpi_environment_t mpi;
   mpi.init(argc, argv);
@@ -156,18 +180,112 @@ cat > $1/main_3d.cpp << EOF
 EOF
 }
 
-if [[ "$#" -ne 1 ]]; then
-    echo "useage: ./$(basename "$0") example"
+help="-- Use this script to create a new example and/or a new .pro file --
+
+usage:
+      ./$(basename "$0") example_name [pro_file_destination]
+    to be executed in the $PARCASL_EXAMPLES_DIR directory
+
+where:
+    example_name is the name of the example whose creation/configuration is desired. If it does not
+    exist, the example folder will be created, generic configuration files will be added and dummy
+    main files will be created as well. If the example folder already exists, the script will create
+    and add any missing configuration file(s) and it will create dummy main files if no main file is
+    to be found in the existing directory.
+
+    pro_file_destination is the name of the directory where a new .pro file will be placed. If the
+    directory does not exist, it will be created. If not provided, a new .pro file will be created
+    in the example folder (i.e, $PARCASL_EXAMPLES_DIR/example_name/)
+
+The user needs to have defined the following environment variable
+    CASL_P4EST_USER:  environment specifier
+as it is required to create the corresponding qmake .pro file.
+
+If not defined yet, define it by executing
+export CASL_P4EST_USER=basename of the specific .pri file in $PARCASL_DIR/qmake
+                       that defines the specific build environment of your machine (specific paths
+                       to external libaries, specific compilers, etc.). If it does not exist yet,
+                       create it by executing the script
+                          ./new_environment
+                       in $PARCASL_DIR/qmake, with the appropriate environment variables (see help of
+                       that script for more details).
+"
+
+directory_instruction="This script can only be executed from the $PARCASL_EXAMPLES_DIR directory.
+Change directory and execute again, i.e. do the following
+  cd $PARCASL_EXAMPLES_DIR
+  ./$(basename "$0") "$1" "$2"
+"
+
+if { [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; } || [ "$1" == "-h" ] || [ "$1" == "-help" ]; then
+    echo "$help"
+    exit 1;
+elif [[ "$PWD" != "$PARCASL_EXAMPLES_DIR" ]]; then
+    echo "$directory_instruction"
+    exit 1;
 else
   name=$1
 
-  # create a new example only if one does not exist with the same name
-  if [[ ! -e $name ]]; then
-    mkdir $name
-    create_pro $name
-    create_main $name
+  if [ "$#" -eq 2 ]; then
+    pro_dir=$2
   else
-    echo "ERROR: Example '$name' already exists. Please choose another name."
+    pro_dir=$1
+  fi
+
+  # create a new example only if one does not exist with the same name
+  if [ ! -e ${name} ] || { [ -e ${name} ] && [ ! -f ${pro_dir}/${name}.pro ]; } || { [ -e ${name} ] && [ ! "$(ls ${name}/main*.cpp 2>/dev/null)" ] ; }; then
+    if [ ! -e ${name} ]; then
+      echo "Creating directory ./${name}"
+      mkdir ${name}
+    fi
+    if [ ! -e ${pro_dir} ]; then
+      echo "Creating directory ${pro_dir}"
+      mkdir -p ${pro_dir}
+      if [ ! -e ${pro_dir} ]; then
+        exit 1;
+      fi
+    fi
+    if [ -e ${name} ] && [ ! -f ${pro_dir}/${name}.pro ]; then
+      # we will need to create the .pro file, so we will need CASL_P4EST_USER to be defined
+      if [ ! -d ${PARCASL_DIR} ]; then
+        echo "The parent directory is not valid: are you sure you are running the script in the example folder of the casl_p4est repository?"
+        exit 1
+      fi
+      if [ -z ${CASL_P4EST_USER} ]; then
+        echo "ERROR: The environment variable CASL_P4EST_USER is undefined."
+        echo "CASL_P4EST_USER needs to be defined and to refer to the basename of an environment-specific file in ${PARCASL_DIR}/qmake."
+        exit 1
+      elif [ ! -d ${PARCASL_DIR}/qmake ]; then
+        echo "ERROR: the qmake directory ${PARCASL_DIR}/qmake cannot be found..."
+        echo "Are you sure PARCASL_DIR=${PARCASL_DIR} is correct?"
+        exit 1
+      elif [ ! -f ${PARCASL_DIR}/qmake/${CASL_P4EST_USER}.pri ]; then
+        echo "ERROR: the environment-specific file ${PARCASL_DIR}/qmake/${CASL_P4EST_USER}.pri does not exist."
+        echo "Please create it by executing ./new_environment in ${PARCASL_DIR}/qmake, first."
+        exit 1
+      fi
+
+      echo "Creating the .pro file."
+      cd $pro_dir
+      create_pro $name $PARCASL_DIR
+      cd ${PARCASL_DIR}/examples/
+
+      cd $name
+      if [ ! -e $name.pri ]; then
+        create_pri $name
+      else
+        echo "The source list '$name.pri' already exists: please check if it is valid."
+      fi
+      cd ../
+    fi
+    if { [ -e ${name} ] && [ ! "$(ls ${name}/main*.cpp 2>/dev/null)" ] ;  }; then
+      echo "No existing main file: creating dummy 2d and 3d main files."
+      create_dummy_main ${name}
+    fi
+  else
+    echo "ERROR: Example '${name}' already exists and is already fully configured. Please go ahead or choose another name."
     exit 1
-  fi  
+  fi
 fi
+
+
