small changes to the qmake build configs

diff --git a/examples/newexample b/examples/newexample
--- a/examples/newexample
+++ b/examples/newexample
@@ -1,7 +1,6 @@
 #!/usr/bin/env bash
 
-# Use this script to create a sample example which creats a tree 
-# and saves it into a vtk file.
+# Use this script to create a bare minimum example 
 # 
 # Usage:
 #   ./create_example name [config]
@@ -10,21 +9,16 @@
 # creates a .pro file 
 function create_pro() {
 cat > $1/$1.pro << EOF
-# --------------------------------------------------------------
-# qmake config file for the $1 example
-# --------------------------------------------------------------
-CONFIG += 2d
-
-include(../../config/$2.pri)
+CONFIG += 2d $2
 include(../../config/libparcasl.pri)
 
 CONFIG(2d, 2d|3d): {
-  TARGET = $1_2d
+  TARGET   = $1_2d
   SOURCES += main_2d.cpp
 }
 
 CONFIG(3d, 2d|3d): {
-  TARGET = $1_3d
+  TARGET   = $1_3d
   SOURCES += main_3d.cpp
 }
 
@@ -144,25 +138,24 @@ EOF
 }
 
 if [[ "$#" -ne 1 ]]; then
-    echo "useage: $(basename "$0") name [config]\n"\
-         "'name'  : name of the example file (will be skipped if already exist)\n"\
-         "'config': configuration to be used for finding dependencies (defaults to homebrew)"
+    echo "useage: ./$(basename "$0") example [config]"
 else
-	name=$1
+  name=$1
   config=$2
 
   # check if a config is set, if not set it to homebrew 
   if [[ -z $config ]]; then
-    config="homebrew"
+    config="macx"
   fi
 
+
   # create a new example only if one does not exist with the same name
-	if [[ ! -e $name ]]; then
-		mkdir $name
+  if [[ ! -e $name ]]; then
+    mkdir $name
     create_pro $name $config
     create_main $name
-	else
-		echo "Example '$name' already exists. Please choose another name."
-		exit 1
-	fi	
+  else
+    echo "ERROR: Example '$name' already exists. Please choose another name."
+    exit 1
+  fi  
 fi
